### PR TITLE
Replace 'Array' with 'ContiguousArray'

### PR DESCRIPTION
**Pull request by shoheiyokoyama**
## Description

`Reducer` and `Middleware` are aliases of closure. closure is `Reference Type` as [apple doc](https://docs.swift.org/swift-book/LanguageGuide/Closures.html)

Array of reference types should use `ContiguousArray`.
For `ContiguousArray`, it is described in Apple document as follows.

> If you need an array of reference types and the array does not need to be bridged to NSArray, use ContiguousArray instead of Array
Ref: [Advice: Use ContiguousArray with reference types when NSArray bridging is unnecessary](https://github.com/apple/swift/blob/master/docs/OptimizationTips.rst#advice-use-contiguousarray-with-reference-types-when-nsarray-bridging-is-unnecessary)

> using ContiguousArray may be more efficient and have more predictable performance than Array. 
Ref: [ContiguousArray](https://developer.apple.com/documentation/swift/contiguousarray?changes=_5)

I replaced `Array` type of `reducers` and `middlewares` with ` ContiguousArray`.

## Checklist

- [x] this PR is based on develop or a 'develop related' branch
- [x] the commits inside this PR have explicit commit messages
- [x] the Jazzy documentation has been generated (if needed -> Jazzy RxReduce)

### CODE REVIEW

**Comment by shoheiyokoyama** [comment]
@twittemb
What is the option to generate Jazzy documentation? author, author_url, github_url, etc.

**Comment by twittemb** [comment]
Hi

In general I pass no particular option, just 'jazzy RxReduxe'

**Comment by shoheiyokoyama** [comment]
@twittemb 
I just updated jazzy documentation.

**Comment by twittemb** [comment]
Thanks. I didn't know about Contiguous arrays. Thanks for sharing all the optimization tips.

I'll merge the PR asap.

👍

**Review by twittemb — APPROVED** [review]

**Comment by twittemb** [comment]
Thanks @shoheiyokoyama

**Pull request merged**
